name: Android build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: setup jdk
      uses: actions/setup-jdk@v1
      with:
        java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew assemble